### ISSUE TITLE
Expand utterance format

### ISSUE THREAD

**Issue by cogitantium** [Badgie/utterance#1]
One way to expand the use-case of the project could be to allow for other types of data, e.g. images, etc. This could also be an exercise in Python generics, probably.

I see a use-case for a group posting memes on their door in a somewhat rapid frequency that could use this feature.

**Comment by Badgie** [comment]
Resolved with c29f62771ace2e8eea5ace985e6ff3a7235ce003 and 71b6657db10b30cdc129e3ff2b247fa46f5367eb
